[package]
name = "hydraulics-model"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
friction = {path = "friction"}

[[bin]]
name = "hydraulics-model"
path = "src/main.rs"
